# -*- coding: utf-8 -*-

# 配置相关参数
log_to_file: False
model_type: "Net"
dataset: "mnist"
checkpoint_path: "result/model_save"
train_input_path:
test_input_path:
save_model_path: "result/model_save"
result_path: "result"
random_seed: 123456
save_whole_modle: False # 模型保存时最好结果保存整个模型

# 训练相关参数
begin_epoch: 1   # 继续训练
epochs: 5
early_stop_num: 3 # 连续几次acc不增加就停止训练
batch_size: 128
ratio: 0.8 #train/val 比例
learning_rate: 0.0001
learning_rate_decay_rate: 0.1
learning_rate_decay_epochs: 5

# 多GPU
distributed: True
syncBN: True
pin_memory: True